temp fix due to asset missing
  File "/home/jon/.local/lib/python3.10/site-packages/ee/data.py", line 404, in _execute_cloud_call
    raise _translate_cloud_exception(e)  # pylint: disable=raise-missing-from
ee.ee_exception.EEException: Collection.loadTable: Collection asset 'projects/ee-andyarnellgee/assets/p0004_commodity_mapper_support/raw/KBAsGlobal_2023_March_01_POL' not found